CREATE TABLE I18N_MESSAGE (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 고유 식별자
    CODE        VARCHAR2(100) NOT NULL,                              -- 메시지 키
    LOCALE      VARCHAR2(10)  NOT NULL,                              -- 언어 코드 (ko, en, ja 등)
    MESSAGE     NVARCHAR2(1000) NOT NULL,                            -- 다국어 메세지 (NVARCHAR2 권장)
    DESCRIPTION VARCHAR2(4000),                                      -- 설명
    CREATED_AT  DATE DEFAULT SYSDATE,                                -- 생성일
    
    -- 동일 코드 + 동일 언어 중복 방지 제약 조건
    CONSTRAINT UK_I18N_CODE_LOCALE UNIQUE (CODE, LOCALE)
);

-- 코드별 조회가 빈번하므로 인덱스 생성
CREATE INDEX IX_I18N_CODE ON I18N_MESSAGE (CODE);
-- 한국어 (ko)
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('common.save', 'ko', '저장');
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('common.cancel', 'ko', '취소');
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('login.welcome', 'ko', '반갑습니다, :name님!');

-- 영어 (en)
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('common.save', 'en', 'Save');
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('common.cancel', 'en', 'Cancel');
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('login.welcome', 'en', 'Welcome, :name!');

-- 일본어 (ja)
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('common.save', 'ja', '保存');
INSERT INTO I18N_MESSAGE (CODE, LOCALE, MESSAGE) VALUES ('common.cancel', 'ja', 'キャンセル');

COMMIT;


DROP TABLE CALENDAR;
CREATE TABLE CALENDAR(
	ID NUMBER PRIMARY KEY,
	TITLE VARCHAR2(100),
	WRITER VARCHAR2(50),
	START1 DATE,
	END1 DATE,
	CONTENT VARCHAR2(1000),
	BACKGROUND_COLOR VARCHAR2(50),
	TEXT_COLOR VARCHAR2(50),
	ALL_DAY NUMBER(1),
	URL_LINK VARCHAR2(50)
);
INSERT INTO CALENDAR VALUES(CALENDAR_SEQ.NEXTVAL, '첫일정','홍길동','2025-07-11','2025-07-12','첫일정입니다.',
							'#0099CC', '#CCFFFF',1, 'http://www.nanver.com');
INSERT INTO CALENDAR VALUES(CALENDAR_SEQ.NEXTVAL, '두번일정','홍길동','2025-07-14','2025-07-15','두일정입니다.',
							'#0099CC', '#CCFFFF',1, 'http://www.nanver.com');
INSERT INTO CALENDAR VALUES(CALENDAR_SEQ.NEXTVAL, '세번일정','홍길동','2025-07-15','2025-07-16','세번일정입니다.',
							'#0099CC', '#CCFFFF',1, 'http://www.nanver.com');


SELECT * FROM calendar;
