DROP TABLE BOARD CASCADE CONSTRAINTS;

		CREATE TABLE BOARD(
			NO NUMBER PRIMARY KEY,  -- 글번호(기본키)
			REFNO NUMBER,  -- 답글번호
			SUBJECT VARCHAR2(100),  -- 제목
			CONTENT VARCHAR2(1000), -- 내용
			WRITER VARCHAR2(50), -- 작성자
			READCNT NUMBER, -- 조회수
			REGDTE DATE, -- 등록일
			UPTDTE DATE  -- 수정일
		);
		CREATE TABLE BOARDFILE (
			NO NUMBER,
			FNAME VARCHAR2(100),
			ETC VARCHAR2(500),
			REGDTE DATE,
			UPTDTE DATE
		);		
		CREATE TABLE ANNOUNCEFILE(
			NO NUMBER,
			FNAME VARCHAR2(100),
			ETC VARCHAR2(500),
			REGDTE DATE,
			UPTDTE DATE
		);
		
		
SELECT * FROM MEMBER;		
		CREATE SEQUENCE BOARD_SEQ;
		INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,0,'첫번째글','내용없음','홍길동',0,SYSDATE, SYSDATE);
SELECT * FROM board;		